from gpiozero import Button, LED


NORTH_RED = LED("BOARD5")
NORTH_GREEN = LED("BOARD3")
EAST_RED = LED("BOARD19")
EAST_YELLOW = LED("BOARD21")
EAST_GREEN = LED("BOARD15")
SOUTH_RED = LED("BOARD11")
SOUTH_GREEN = LED("BOARD7")
WEST_RED = LED("BOARD13")
WEST_YELLOW = LED("BOARD29")
WEST_GREEN = LED("BOARD23")

NORTH_RED, NORTH_GREEN, EAST_RED, EAST_YELLOW, EAST_GREEN, SOUTH_RED, SOUTH_GREEN, WEST_RED, WEST_YELLOW, WEST_GREEN

ALL = [NORTH_RED, NORTH_GREEN, EAST_RED, EAST_YELLOW, EAST_GREEN, SOUTH_RED, SOUTH_GREEN, WEST_RED, WEST_YELLOW, WEST_GREEN]

REDS = [NORTH_RED, EAST_RED, SOUTH_RED, WEST_RED]
YELLOWS = [EAST_YELLOW, WEST_YELLOW]
GREENS = [NORTH_GREEN, EAST_GREEN, SOUTH_GREEN, WEST_GREEN]

NORTH = [NORTH_RED, NORTH_GREEN]
EAST = [EAST_RED, EAST_YELLOW, EAST_GREEN]
SOUTH = [SOUTH_RED, SOUTH_GREEN]
WEST = [WEST_RED, WEST_YELLOW, WEST_GREEN]

ON = Button("BOARD8")
OFF = Button("BOARD10")
MANUAL = Button("BOARD12")
AUTO = Button("BOARD16")
BUTTON = Button("BOARD18", bounce_time=500)

IN = [ON, OFF, MANUAL, AUTO, BUTTON]

BUTTON_PRESSED = False

MODE_OFF = 1
MODE_MANUAL = 2
MODE_STANDUP = 3
MODE_LUNCH = 4
MODE_STATUS = 5


def main():
    for led in ALL:
        led.off()
